//
//  Resource.swift
//  XmlPasing
//
//  Created by 박영호 on 2020/11/04.
//

import UIKit

class Resource {
    static let shared = Resource()
    
    var koreaDictionary = Dictionary<Keys, String>()
    var thailandDictionary = Dictionary<Keys, String>()
    
    func getKoreaValue(key: Keys, arguments: Any...) -> String {
        guard var result = koreaDictionary[key] else {
            return ""
        }
        result = String(format: result, arguments: arguments as! [CVarArg])
        return result
    }
    
    func getThailandValue(key: Keys, arguments: Any...) -> String {
        guard var result = thailandDictionary[key] else {
            return ""
        }
        result = String(format: result, arguments: arguments as! [CVarArg])
        return result
    }
}

enum Keys: String {
    case trash
    
    case app_name
    case bottom_nav_title_home
    case bottom_nav_title_search
    case bottom_nav_title_my
    case bottom_nav_title_setting
    case play_time
    case max_size
    case artist
    case expire_date
    case content_basic_info
    case buffering_info
    case buffering_info_other
    case buffering_button1
    case buffering_button2
    case buffering_button3
    case reply_hint
    case reply
    case register
    case reply_not_permit
    case report_limit
    case download
    case downloading
    case no
    case yes
    case cancel
    case save
    case pause
    case restart
    case retry
    case play
    case play_now
    case see_more
    case see_more_close
    case check_network
    case go_to_mydownload
    case leave
    case download_paused
    case view_detail
    case permission_title
    case permission_app_name
    case permission_app_desc
    case permission_phone
    case permission_phone_desc
    case permission_storage
    case permission_storage_desc
    case permission_camera
    case permission_camera_desc
    case permission_mic
    case permission_mic_desc
    case permission_location
    case permission_location_desc
    case popup_turn_off_today
    case popup_turn_off
    case agreement_title
    case agreement_desc
    case agreement_usage
    case agreement_private_info
    case agreement_info_process
    case agreement_marketing
    case agreement_extra_desc
    case agreement_warn
    case agreement_all
    case agreement_marketing_info
    case agree_cancel_notice
    case see_underline
    case next
    case close
    case ok
    case exit
    case keep
    case prev_version
    case next_version
    case agreement_and_go
    case close_app_confirm
    case theme_view_all
    case like
    case share
    case share_jpg
    case share_gif
    case share_mp4
    case my_recently_viewed
    case my_download
    case my_like
    case my_replies
    case my_contents
    case my_album
    case delete
    case font_error
    case share_content
    case my_contents_selection_delete
    case my_contents_selection_delete_confirm
    case my_contents_camera
    case my_contents_3d
    case my_contents_
    case qlone_no_contents
    case qlone_tutorial_need_mat
    case qlone_tutorial_download_btn
    case qlone_tutorial_do_landscape
    case qlone_tutorial_360_scan
    case qlone_tutorial_360_scan_msg
    case qlone_tutorial_keep_scan
    case qlone_tutorial_other_scan
    case qlone_tutorial_after_scan
    case qlone_tutorial_after_scan_2
    case qlone_make_name_desc
    case qlone_make_name_hint
    case qlone_exit_scanning_desc
    case qlone_exit_not_saved_desc
    case qlone_select_share_type_title
    case qlone_randering
    case setting_event
    case setting_notice
    case setting_faq
    case setting_question
    case setting_other
    case select_all
    case setting_nickname
    case setting_push
    case setting_push_desc
    case setting_continuous_play
    case setting_continuous_play_desc
    case setting_bright_theme
    case setting_contents_save
    case setting_app_version
    case setting_current_version
    case setting_opensource_licence
    case setting_terms_of_service
    case setting_private_policy
    case setting_private_policy_collection
    case setting_private_policy_terms
    case setting_update_agreement
    case setting_nick_current_nick
    case setting_nick_change_nick_hint
    case setting_nick_change_nick_success
    case setting_nick_change_nick_duplicate
    case setting_version_update
    case setting_select_storage
    case setting_update_disagree_last_version
    case setting_question_title2
    case setting_question_title3
    case setting_question_hint_email
    case setting_question_hint
    case setting_question_agreement
    case setting_question_send
    case setting_question_dialog
    case setting_question_toast
    case setting_question_failure
    case setting_question_title
    case setting_question_type_select2
    case setting_question_type_select
    case setting_question_type_app_usage
    case setting_question_type_price_data
    case setting_question_type_contents_quality
    case setting_question_type_event
    case setting_question_type_others
    case setting_question_type_feedback
    case setting_event_apply
    case setting_internal_storage
    case setting_sd_card
    case setting_available_space
    case setting_change_space
    case contents
    case writer
    case report
    case report_select_reason
    case report_reason_1
    case report_reason_2
    case report_reason_3
    case report_complete
    case etc
    case report_hint_detail
    case player_reply
    case player_reply_please_enter
    case player_no_reply
    case player_searching_surface_toast
    case player_unsupported_device
    case player_save_preview
    case player_video_recording_end
    case player_play_done
    case today
    case yesterday
    case two_days_ago
    case three_days_ago
    case four_days_ago
    case five_days_ago
    case six_days_ago
    case seven_days_ago
    case order_date
    case order_size
    case update_popup_major
    case update_popup_miner
    case later
    case update
    case save_file_out_of_storage
    case move_to_setting
    case preview_exit_without_save
    case could_not_open_page
    case error_occurred
    case network_error
    case network_error_too_many
    case network_error_wifi
    case network_error_cell
    case server_error
    case my_recently_viewed_empty
    case my_download_empty
    case my_like_empty
    case my_reply_empty
    case my_contents_empty
    case my_contents_see_other
    case network_error_splash
    case roaming_status_dialog
    case roaming_status
    case usim_not_inserted
    case insufficient_storage
    case contents_expiration
    case reply_reported
    case deleted_contents
    case reply_not_entered
    case reply_overflow
    case reply_add_completed
    case reply_add_failed
    case reply_include_slang
    case reply_delete_completed
    case reply_delete_failed
    case download_completed
    case cancel_download
    case cannot_contents_3d_streaming
    case cannot_contents_lte_streaming
    case cannot_lte_warning
    case download_failed
    case download_retry
    case download_resumed
    case recently_viewed_contents_max_limited
    case reply_delete_warn
    case reply_delete
    case delete_contents_warn
    case delete_contents_completed
    case delete_contents_failed
    case reply_report_failed
    case play_failed
    case dialog_play_next_wating
    case dialog_play_next_wating_remaining
    case dialog_play_next_setting_change
    case dialog_cell_warning
    case dialog_streaming_warning
    case dialog_ar_caution1
    case dialog_ar_caution2
    case register_user_completed
    case permission_rational_desc
    case setting_now
    case setting_later
    case third_party_user_notice
    case third_party_user_preview_notice_mvno
    case third_party_user_preview_notice
    case internal_storage_required_size_exceed
    case contents_turn_off
    case preview_end_alert
    case streaming_alert_lte_toast
    case streaming_alert_wifi_toast
    case contents_lte_download_toast
    case contents_3d_download_toast
    case streaming_alert_5g
    case streaming_alert_lte
    case download_info_5g
    case data_saving_mode_warn
    case please_recognize_image
    case please_recognize_fail
    case move_google_lens
    case start_event_page_after_3s
    case see_stillcut
    case contents_stillcut
    case contents_preview
    case until_format
    case tutorial_onboarding_0_title
    case tutorial_onboarding_1_title
    case tutorial_onboarding_2_title
    case player_tutorial_title_0
    case player_tutorial_title_1
    case player_tutorial_title_2
    case player_tutorial_title_3
    case player_tutorial_desc_1
    case player_tutorial_desc_2
    case player_tutorial_desc_3
    case player_floor_tutorial_title_0
    case player_floor_tutorial_title_1
    case player_floor_tutorial_desc_0
    case player_floor_tutorial_desc_1
    case intro_start
    case intro_skip
    case tutorial_txt_1
    case tutorial_txt_2
    case thousand
    case ten_thousand
    case billion
    case lge_special
    case search_hint1
    case search_theme_contents
    case view_all
    case delete_all
    case trends
    case search_recent
    case search_related
    case search_result_null
    case search_result
    case take_shot
    case switch_camera
    case my_contents_link
    case warning_temperature
    case qlone_same_name
    case qlone_name_have_blink
    case qlone_name_have_special
    case qlone_limit_name
    case downloadable_content
    case streaming_cotent_mid_quality
    case streaming_content_high_quality
    case streaming_content_ultra_quality
    case performance
    case sticker
    case threed_character
    case home_thumb
    case hot_thumb
    case new_thumb
    case my_thumb
    case content_path_string
    case copying
    case event_detail_desc1
    case event_detal_desc2
    case excute_recog_image
    case force_set_5G
    case all_network_set
    case test_play_btn
    case apply_after_app_start
    case change_server
    case pls_restart_app_after_change_server
    case speed_test
    case test_for_change_ctn
    case pls_restart_app_after_change
    case test_mode_search
    case term_agree_screen
    case init_turorial
    case inspection
    case inspect_content_list
    case program_test_list
    case inspect_local_content_list
    case term_agree
    case video
    case animated
    case photo
    case tile_bts_promotion
    case thumbnail
    case program
    case playback
    case text
    case gif
    case title_notice
    case title_notice_title_notice
    case replay_content_replay_content
    case seolhyun
    case fcm_id_confirm
    case all_confirm_agree
    case copied_to_clipboard
    case invalid_uri
    case mandatory_folder_not_found
    case debug_set_ok
    case to_inspect_mode_set
    case remain_count
    case inspect_mode_setted
    case theme
    case not_supported_your_device
    case network_error_before_login
}
