# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20200904ConstraintTraining' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20200904ConstraintTraining
  pod 'RxSwift',    '~> 5'
  pod 'RxCocoa',    '~> 5'
  pod 'RxFlow'
  pod 'RxOptional'
  pod 'RxSwiftExt'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'Cell+Rx'
  pod 'Action'

  pod 'Then'
  pod 'SnapKit'
  pod 'Reusable'
  
  pod 'SDWebImage'
  pod 'lottie-ios'
  
end
