# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoundationProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoundationProj
 
    #pod 'Alamofire', '~> 4.8'
  pod 'Moya/RxSwift',   '~> 14.0'
  
  pod 'RxSwift',    '~> 5'
  pod 'RxCocoa',    '~> 5'
  pod 'RxFlow'
  pod 'RxOptional'
  pod 'RxSwiftExt'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'Cell+Rx'
  
  pod 'Action'

  pod 'SwiftLint'
  pod 'KeychainSwift'
  pod 'SnapKit'
  pod 'Reusable'
  pod 'Then'
  
  # Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/DynamicLinks'
  
  # Firebase CloudStore Codable Extension
  pod 'CodableFirebase'
  
  pod 'CryptoSwift', '~> 1.0'
  
  # Image
  pod 'SDWebImage', '~> 5.0'
  pod 'lottie-ios'
  
  # Database
  pod 'RealmSwift'
  pod "RxRealm"
  pod 'Unrealm'
  
  # zip
  pod 'Zip', '~> 1.1'
  
  # font customing
  pod 'BonMot'
end

target 'FoundationProjTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'FoundationProjUITests' do
  # Pods for testing
end

